### ISSUE TITLE
Waiting results from OpenAI... all the time

### ISSUE THREAD

**Issue by PIDAN-HEIDASHUAI** [hisxo/ReconAIzer#12]
My setting:
Windows10
BP professional 2022.3.8
Jython 2.7.3
ReconAIzer 0.7

Jython：
<img width="819" alt="2023-05-08 10_26_40-Burp Suite Professional v2022 3 8 - Temporary Project - OPAO" src="https://user-images.githubusercontent.com/130355261/236720640-5710b28f-7278-4fbd-b0be-7cb04580560a.png">
ReconAIzer：
<img width="555" alt="2- OPAO" src="https://user-images.githubusercontent.com/130355261/236720654-52007444-ffa8-4235-8604-2ea2650a2407.png">
ReconAIzer Config：
<img width="284" alt="3 OPAO" src="https://user-images.githubusercontent.com/130355261/236720670-80f52c54-4825-4d40-84ab-b8704e831ff7.png">
ReconAIzer Results：
<img width="363" alt="4OPAO" src="https://user-images.githubusercontent.com/130355261/236720687-58a923d5-18cf-482a-aae7-2a1609453ea2.png">
It show "Waiting results from OpenAI..."  all the time, I checked the question on github and Google and there was nothing the same.
I'd appreciate it if you could help me out. Thank you so much!

**Comment by hisxo** [comment]
Hello,

Could you check the output of the extension and tell me if something is returned here?

![image](https://user-images.githubusercontent.com/16657045/236852991-dfef0cef-de19-472b-bc1c-b9b525d99230.png)

Thanks!

**Comment by PIDAN-HEIDASHUAI** [comment]
> Hello,
> 
> Could you check the output of the extension and tell me if something is returned here?
> 
> ![image](https://user-images.githubusercontent.com/16657045/236852991-dfef0cef-de19-472b-bc1c-b9b525d99230.png)
> 
> Thanks!

Hello,
Thanks for your reply. Here is the picture, It's blank.
<img width="561" alt="1PAO" src="https://user-images.githubusercontent.com/130355261/237031167-c1a90437-1c61-403e-b1a3-19b30bddd08a.png">
Thank you again for your reply!

**Comment by shelu16** [comment]
Traceback (most recent call last):
  File "G:\Burp\ReconAIzer.v0.7.py", line 132, in run
    api_result = self.extender.send_request_to_openai(text, self.prompt_type)
  File "G:\Burp\ReconAIzer.v0.7.py", line 203, in send_request_to_openai
    raise Exception("API request failed with response code: {}".format(response_code))
Exception: API request failed with response code: 401

**Comment by hisxo** [comment]
Do you have a paid plan account on OpenAI ? This 401 error mean that you have probably a free account, so you can't use the API.

Regards,
Hisxo

**Comment by shelu16** [comment]
ok
