### ISSUE TITLE
API Key line number incorrect in Readme

### ISSUE THREAD

**Issue by zachisparanoid** [hisxo/ReconAIzer#7]
Readme states to add your personal API key on "line 103".  API Key is referenced on "line 115" of the python script.  Likely has been moved down due to additions to the code.  Just a heads up.

![image](https://user-images.githubusercontent.com/4337011/231507130-2151a202-3824-4179-9308-4c0d32c27e13.png)

**Comment by hisxo** [comment]
Hello,

It's fixed, the API key is now configured directly on the UI instead of the file.

Hisxo
